version: "3.0"

services:
  dask-distributed-worker:
    build: .
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
      - "${NANNY_PORT}:${NANNY_PORT}"
      - "${BOKEH_PORT}:${BOKEH_PORT}"
    restart: always
    command: >
      "source activate xcube && dask-worker --listen-address 'tcp://0.0.0.0:${WORKER_PORT}' --contact-address 'tcp://192.168.1.168:${WORKER_PORT}' --nanny-port ${NANNY_PORT} --dashboard-address 0.0.0.0:${BOKEH_PORT} ${SCHEDULER_ADDRESS}:${SCHEDULER_PORT}"
    volumes:
      - /data/datacube:/data/datacube
      - /home/jovyan/work/datacube:/home/jovyan/work/datacube
    healthcheck:
      test: ["CMD", "curl", "localhost:8786"]
      interval: 30s

