version: "3.0"

services:
  dask-distributed-worker:
    build: .
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
      - "${NANNY_PORT}:${NANNY_PORT}"
      - "${BOKEH_PORT}:${BOKEH_PORT}"
    command: >
      "source activate xcube && dask-worker --worker-port ${WORKER_PORT} --nanny-port ${NANNY_PORT} --dashboard-address 0.0.0.0:${BOKEH_PORT} ${SCHEDULER_ADDRESS}:${SCHEDULER_PORT}"
    volumes:
      - /data/datacube:/home/jovyan/work/datacube
    healthcheck:
      test: ["CMD", "curl", "localhost:8786"]
      interval: 30s

