version: "3.0"

services:
  dask-distributed-worker:
    build: .
    ports:
      - "${WORKER_PORT}:${WORKER_PORT}"
      - "${NANNY_PORT}:${NANNY_PORT}"
      - "${BOKEH_PORT}:${BOKEH_PORT}"
    command: >
      "source activate xcube && dask-worker --worker-port ${WORKER_PORT} --nanny-port 9001 --dashboard-address 0.0.0.0:9002 192.168.1.164:8786"
    healthcheck:
      test: ["CMD", "curl", "localhost:8786"]
      interval: 30s

