version: "3.0"

services:
  jupyter-lab:
    build: .
    ports:
      - "80:8888"
    volumes:
      - /mnt/efs/data:/data
    restart: always
    command: >
      "source activate xcube && jupyter lab --ip 0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "localhost:8888"]
      interval: 30s

