version: "3.0"

services:
  dask-distributed-scheduler:
    build: .
    ports:
      - "${SCHEDULER_PORT}:${SCHEDULER_PORT}"
      - "${BOKEH_PORT}:${BOKEH_PORT}"
    restart: always
    command: >
      "source activate xcube && dask-scheduler"
    healthcheck:
      test: ["CMD", "curl", "localhost:${BOKEH_PORT}"]
      interval: 30s

